name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - commit-injection

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@6792

    - name: Check
      run: python3 ci_check.py
